apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.labels.app }}-deployment
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
    spec:
      containers:
        - name: {{ .Values.metadata.labels.app }}-container
          image: {{ .Values.containers.image }}:{{ .Values.containers.imagetag }}
          envFrom:
            - configMapRef:
                name: {{ .Values.metadata.labels.app }}-configmap
            - secretRef:
                name: {{ .Values.metadata.labels.app }}-db-secret
            - secretRef:
                name: {{ .Values.metadata.labels.app }}-rabbitmq-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: {{ .Values.containers.ports.containerPort }}
#            initialDelaySeconds: 60
#            periodSeconds: 10
#            failureThreshold: 5     
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: {{ .Values.containers.ports.containerPort }}
#            initialDelaySeconds: 60
#            periodSeconds: 10
#            failureThreshold: 5          
          ports:
            - containerPort: {{ .Values.containers.ports.containerPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      imagePullSecrets:
        - name: ecr-cred
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.metadata.labels.app }}-rabbitmq-statefulset
  labels:
    app: {{ .Values.metadata.labels.app }}-rabbitmq
spec:
  replicas: 1
  serviceName: {{ .Values.metadata.labels.app }}-rabbitmq-service
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}-rabbitmq
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}-rabbitmq
    spec:
      containers:
        - name: {{ .Values.metadata.labels.app }}-rabbitmq-container
          image: "public.ecr.aws/docker/library/rabbitmq:3-management"
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.metadata.labels.app }}-rabbitmq-secret
                  key: RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.metadata.labels.app }}-rabbitmq-secret
                  key: RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD
          ports:
          - name: amqp
            containerPort: 5672
            protocol: TCP
          - name: http
            containerPort: 15672
            protocol: TCP
          volumeMounts:
          - name: data
            mountPath: "/var/lib/rabbitmq/mnesia"
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.metadata.labels.app }}-postgresql-statefulset
  labels:
spec:
  replicas: 1
  serviceName: {{ .Values.metadata.labels.app }}-postgresql-service
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}-postgresql
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}-postgresql
    spec:
      containers:
        - name: {{ .Values.metadata.labels.app }}-postgresql-container
          image: "public.ecr.aws/docker/library/postgres:16.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: orders
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.metadata.labels.app }}-db-secret
                  key: RETAIL_ORDERS_PERSISTENCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.metadata.labels.app }}-db-secret
                  key: RETAIL_ORDERS_PERSISTENCE_PASSWORD
            - name: PGDATA
              value: /data/pgdata
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
      volumes:
      - name: data
        emptyDir: {}