apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metadata.labels.app }}-db-secret
data:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: "b3JkZXJz"
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: "eGl4aE5TQU43Y2hQV0RSNg=="