apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metadata.labels.app }}-db-secret
data:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: "b3JkZXJz"
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: "eGl4aE5TQU43Y2hQV0RSNg=="
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metadata.labels.app }}-rabbitmq-secret
data:
  RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME: cmFiYml0bXE=
  RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD: cmFiYml0bXE=