apiVersion: v1
kind: Service
metadata:
  name: retail-store-order-service
  labels:
    app: retail-store-order
spec:
  selector:
    app: retail-store-order
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort